version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    working_dir: /app
    command: npm start
    environment:
      - PORT=3000
    networks:
      - private-net
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    networks:
      - private-net

  proxy:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80
    links:
      - app
    networks:
      - private-net

networks:
  private-net:
    driver: bridge
